-- Everforest colorscheme for Neovim
-- Palette from Helix everforest dark medium theme

local M = {}

local palette = {
  bg_dim = "#232a2e",
  bg0 = "#2d353b",
  bg1 = "#343f44",
  bg2 = "#3d484d",
  bg3 = "#475258",
  bg4 = "#4f585e",
  bg5 = "#56635f",
  bg_visual = "#543a48",
  bg_red = "#514045",
  bg_green = "#425047",
  bg_blue = "#3a515d",
  bg_yellow = "#4d4c43",
  fg = "#d3c6aa",
  red = "#e67e80",
  orange = "#e69875",
  yellow = "#dbbc7f",
  green = "#a7c080",
  aqua = "#83c092",
  blue = "#7fbbb3",
  purple = "#d699b6",
  grey0 = "#7a8478",
  grey1 = "#859289",
  grey2 = "#9da9a0",
  none = "NONE",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.load()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
  vim.g.colors_name = "everforest"
  vim.o.termguicolors = true

  local p = palette

  -- Core UI
  hi("Normal", { fg = p.fg, bg = p.bg0 })
  hi("NormalFloat", { fg = p.fg, bg = p.bg2 })
  hi("NormalNC", { fg = p.fg, bg = p.bg0 })
  hi("FloatBorder", { fg = p.grey1, bg = p.bg2 })
  hi("FloatTitle", { fg = p.orange, bg = p.bg2, bold = true })
  hi("Cursor", { fg = p.bg1, bg = p.grey2 })
  hi("CursorLine", { bg = p.bg1 })
  hi("CursorColumn", { bg = p.bg1 })
  hi("ColorColumn", { bg = p.bg1 })
  hi("LineNr", { fg = p.grey0 })
  hi("CursorLineNr", { fg = p.grey2 })
  hi("SignColumn", { fg = p.fg, bg = p.bg0 })
  hi("FoldColumn", { fg = p.grey0, bg = p.bg0 })
  hi("Folded", { fg = p.grey1, bg = p.bg1 })
  hi("VertSplit", { fg = p.bg4, bg = p.bg_dim })
  hi("WinSeparator", { fg = p.bg4, bg = p.bg_dim })
  hi("StatusLine", { fg = p.grey2, bg = p.bg3 })
  hi("StatusLineNC", { fg = p.grey0, bg = p.bg1 })
  hi("TabLine", { fg = p.grey2, bg = p.bg3 })
  hi("TabLineFill", { bg = p.bg3 })
  hi("TabLineSel", { fg = p.bg0, bg = p.green, bold = true })
  hi("WinBar", { fg = p.grey2, bg = p.bg3 })
  hi("WinBarNC", { fg = p.grey0, bg = p.bg1 })
  hi("Pmenu", { fg = p.fg, bg = p.bg3 })
  hi("PmenuSel", { fg = p.bg0, bg = p.green })
  hi("PmenuSbar", { bg = p.bg3 })
  hi("PmenuThumb", { bg = p.grey0 })
  hi("WildMenu", { fg = p.bg0, bg = p.green })
  hi("Visual", { bg = p.bg3 })
  hi("VisualNOS", { bg = p.bg3 })
  hi("Search", { fg = p.bg0, bg = p.green })
  hi("IncSearch", { fg = p.bg0, bg = p.red })
  hi("CurSearch", { fg = p.bg0, bg = p.red })
  hi("Substitute", { fg = p.bg0, bg = p.yellow })
  hi("MatchParen", { fg = p.orange, bg = p.bg_yellow })
  hi("ModeMsg", { fg = p.fg, bold = true })
  hi("MoreMsg", { fg = p.yellow, bold = true })
  hi("Question", { fg = p.yellow })
  hi("WarningMsg", { fg = p.yellow, bold = true })
  hi("ErrorMsg", { fg = p.red, bold = true })
  hi("Title", { fg = p.orange, bold = true })
  hi("Directory", { fg = p.green })
  hi("SpecialKey", { fg = p.bg4 })
  hi("NonText", { fg = p.bg4 })
  hi("Whitespace", { fg = p.bg4 })
  hi("Conceal", { fg = p.grey0 })
  hi("EndOfBuffer", { fg = p.bg0 })
  hi("SpellBad", { sp = p.red, undercurl = true })
  hi("SpellCap", { sp = p.yellow, undercurl = true })
  hi("SpellLocal", { sp = p.blue, undercurl = true })
  hi("SpellRare", { sp = p.purple, undercurl = true })
  hi("QuickFixLine", { fg = p.purple, bold = true })
  hi("DiffAdd", { bg = p.bg_green })
  hi("DiffChange", { bg = p.bg_blue })
  hi("DiffDelete", { bg = p.bg_red })
  hi("DiffText", { fg = p.bg0, bg = p.blue })

  -- Syntax (fallback for non-treesitter)
  hi("Comment", { fg = p.grey1, italic = true })
  hi("Constant", { fg = p.fg })
  hi("String", { fg = p.aqua })
  hi("Character", { fg = p.aqua })
  hi("Number", { fg = p.purple })
  hi("Boolean", { fg = p.purple })
  hi("Float", { fg = p.purple })
  hi("Identifier", { fg = p.fg })
  hi("Function", { fg = p.green })
  hi("Statement", { fg = p.red })
  hi("Conditional", { fg = p.red })
  hi("Repeat", { fg = p.red })
  hi("Label", { fg = p.orange })
  hi("Operator", { fg = p.orange })
  hi("Keyword", { fg = p.red })
  hi("Exception", { fg = p.red })
  hi("PreProc", { fg = p.purple })
  hi("Include", { fg = p.purple })
  hi("Define", { fg = p.purple })
  hi("Macro", { fg = p.green })
  hi("PreCondit", { fg = p.purple })
  hi("Type", { fg = p.yellow })
  hi("StorageClass", { fg = p.red })
  hi("Structure", { fg = p.yellow })
  hi("Typedef", { fg = p.yellow })
  hi("Special", { fg = p.blue })
  hi("SpecialChar", { fg = p.green })
  hi("Tag", { fg = p.orange })
  hi("Delimiter", { fg = p.grey1 })
  hi("SpecialComment", { fg = p.grey1, italic = true })
  hi("Debug", { fg = p.orange })
  hi("Underlined", { fg = p.blue, underline = true })
  hi("Ignore", { fg = p.grey0 })
  hi("Error", { fg = p.red })
  hi("Todo", { fg = p.purple, bold = true })

  -- Treesitter
  hi("@variable", { fg = p.fg })
  hi("@variable.builtin", { fg = p.purple, italic = true })
  hi("@variable.parameter", { fg = p.fg })
  hi("@variable.member", { fg = p.blue })
  hi("@constant", { fg = p.fg })
  hi("@constant.builtin", { fg = p.purple, italic = true })
  hi("@constant.macro", { fg = p.purple })
  hi("@module", { fg = p.yellow })
  hi("@label", { fg = p.orange })
  hi("@string", { fg = p.aqua })
  hi("@string.documentation", { fg = p.aqua })
  hi("@string.regexp", { fg = p.green })
  hi("@string.escape", { fg = p.green })
  hi("@string.special", { fg = p.yellow })
  hi("@string.special.symbol", { fg = p.aqua })
  hi("@string.special.url", { fg = p.blue, underline = true })
  hi("@character", { fg = p.aqua })
  hi("@character.special", { fg = p.green })
  hi("@boolean", { fg = p.purple })
  hi("@number", { fg = p.purple })
  hi("@number.float", { fg = p.purple })
  hi("@type", { fg = p.yellow })
  hi("@type.builtin", { fg = p.yellow })
  hi("@type.definition", { fg = p.yellow })
  hi("@type.qualifier", { fg = p.red })
  hi("@attribute", { fg = p.purple, italic = true })
  hi("@property", { fg = p.blue })
  hi("@function", { fg = p.green })
  hi("@function.builtin", { fg = p.green })
  hi("@function.call", { fg = p.green })
  hi("@function.macro", { fg = p.green })
  hi("@function.method", { fg = p.green })
  hi("@function.method.call", { fg = p.green })
  hi("@constructor", { fg = p.green })
  hi("@operator", { fg = p.orange })
  hi("@keyword", { fg = p.red })
  hi("@keyword.coroutine", { fg = p.red })
  hi("@keyword.function", { fg = p.red })
  hi("@keyword.operator", { fg = p.orange })
  hi("@keyword.import", { fg = p.purple })
  hi("@keyword.storage", { fg = p.red })
  hi("@keyword.repeat", { fg = p.red })
  hi("@keyword.return", { fg = p.red })
  hi("@keyword.debug", { fg = p.red })
  hi("@keyword.exception", { fg = p.red })
  hi("@keyword.conditional", { fg = p.red })
  hi("@keyword.conditional.ternary", { fg = p.red })
  hi("@keyword.directive", { fg = p.purple })
  hi("@keyword.directive.define", { fg = p.purple })
  hi("@punctuation", { fg = p.grey2 })
  hi("@punctuation.delimiter", { fg = p.grey1 })
  hi("@punctuation.bracket", { fg = p.fg })
  hi("@punctuation.special", { fg = p.blue })
  hi("@comment", { fg = p.grey1, italic = true })
  hi("@comment.documentation", { fg = p.grey1, italic = true })
  hi("@comment.error", { fg = p.red, bold = true })
  hi("@comment.warning", { fg = p.yellow, bold = true })
  hi("@comment.todo", { fg = p.purple, bold = true })
  hi("@comment.note", { fg = p.blue, bold = true })
  hi("@markup.strong", { bold = true })
  hi("@markup.italic", { italic = true })
  hi("@markup.strikethrough", { strikethrough = true })
  hi("@markup.underline", { underline = true })
  hi("@markup.heading", { fg = p.orange, bold = true })
  hi("@markup.heading.1", { fg = p.red, bold = true })
  hi("@markup.heading.2", { fg = p.orange, bold = true })
  hi("@markup.heading.3", { fg = p.yellow, bold = true })
  hi("@markup.heading.4", { fg = p.green, bold = true })
  hi("@markup.heading.5", { fg = p.blue, bold = true })
  hi("@markup.heading.6", { fg = p.purple, bold = true })
  hi("@markup.quote", { fg = p.grey1 })
  hi("@markup.math", { fg = p.blue })
  hi("@markup.link", { fg = p.purple })
  hi("@markup.link.label", { fg = p.orange })
  hi("@markup.link.url", { fg = p.blue, underline = true })
  hi("@markup.raw", { fg = p.green })
  hi("@markup.raw.block", { fg = p.aqua })
  hi("@markup.list", { fg = p.red })
  hi("@markup.list.checked", { fg = p.green })
  hi("@markup.list.unchecked", { fg = p.grey1 })
  hi("@diff.plus", { fg = p.green })
  hi("@diff.minus", { fg = p.red })
  hi("@diff.delta", { fg = p.blue })
  hi("@tag", { fg = p.orange })
  hi("@tag.attribute", { fg = p.green })
  hi("@tag.delimiter", { fg = p.grey1 })

  -- LSP semantic tokens
  hi("@lsp.type.class", { fg = p.yellow })
  hi("@lsp.type.decorator", { fg = p.purple, italic = true })
  hi("@lsp.type.enum", { fg = p.yellow })
  hi("@lsp.type.enumMember", { fg = p.purple })
  hi("@lsp.type.function", { fg = p.green })
  hi("@lsp.type.interface", { fg = p.yellow })
  hi("@lsp.type.macro", { fg = p.green })
  hi("@lsp.type.method", { fg = p.green })
  hi("@lsp.type.namespace", { fg = p.yellow, italic = true })
  hi("@lsp.type.parameter", { fg = p.fg })
  hi("@lsp.type.property", { fg = p.blue })
  hi("@lsp.type.struct", { fg = p.yellow })
  hi("@lsp.type.type", { fg = p.yellow })
  hi("@lsp.type.typeParameter", { fg = p.yellow })
  hi("@lsp.type.variable", { fg = p.fg })
  hi("@lsp.mod.deprecated", { strikethrough = true })

  -- Diagnostics
  hi("DiagnosticError", { fg = p.red })
  hi("DiagnosticWarn", { fg = p.yellow })
  hi("DiagnosticInfo", { fg = p.blue })
  hi("DiagnosticHint", { fg = p.green })
  hi("DiagnosticOk", { fg = p.green })
  hi("DiagnosticUnderlineError", { sp = p.red, undercurl = true })
  hi("DiagnosticUnderlineWarn", { sp = p.yellow, undercurl = true })
  hi("DiagnosticUnderlineInfo", { sp = p.blue, undercurl = true })
  hi("DiagnosticUnderlineHint", { sp = p.green, undercurl = true })
  hi("DiagnosticUnderlineOk", { sp = p.green, undercurl = true })
  hi("DiagnosticVirtualTextError", { fg = p.red, bg = p.bg_red })
  hi("DiagnosticVirtualTextWarn", { fg = p.yellow, bg = p.bg_yellow })
  hi("DiagnosticVirtualTextInfo", { fg = p.blue, bg = p.bg_blue })
  hi("DiagnosticVirtualTextHint", { fg = p.green, bg = p.bg_green })
  hi("DiagnosticFloatingError", { fg = p.red })
  hi("DiagnosticFloatingWarn", { fg = p.yellow })
  hi("DiagnosticFloatingInfo", { fg = p.blue })
  hi("DiagnosticFloatingHint", { fg = p.green })
  hi("DiagnosticSignError", { fg = p.red })
  hi("DiagnosticSignWarn", { fg = p.yellow })
  hi("DiagnosticSignInfo", { fg = p.blue })
  hi("DiagnosticSignHint", { fg = p.green })
  hi("DiagnosticUnnecessary", { fg = p.grey0 })
  hi("DiagnosticDeprecated", { strikethrough = true })

  -- LSP
  hi("LspReferenceText", { bg = p.bg2 })
  hi("LspReferenceRead", { bg = p.bg2 })
  hi("LspReferenceWrite", { bg = p.bg2 })
  hi("LspSignatureActiveParameter", { fg = p.orange, bold = true })
  hi("LspCodeLens", { fg = p.grey0 })
  hi("LspCodeLensSeparator", { fg = p.grey0 })
  hi("LspInlayHint", { fg = p.grey0, bg = p.bg1 })

  -- gitsigns.nvim
  hi("GitSignsAdd", { fg = p.green })
  hi("GitSignsChange", { fg = p.blue })
  hi("GitSignsDelete", { fg = p.red })
  hi("GitSignsAddNr", { fg = p.green })
  hi("GitSignsChangeNr", { fg = p.blue })
  hi("GitSignsDeleteNr", { fg = p.red })
  hi("GitSignsAddLn", { bg = p.bg_green })
  hi("GitSignsChangeLn", { bg = p.bg_blue })
  hi("GitSignsDeleteLn", { bg = p.bg_red })
  hi("GitSignsAddPreview", { fg = p.green })
  hi("GitSignsDeletePreview", { fg = p.red })
  hi("GitSignsCurrentLineBlame", { fg = p.grey0 })
  hi("GitSignsAddInline", { bg = p.bg_green })
  hi("GitSignsChangeInline", { bg = p.bg_blue })
  hi("GitSignsDeleteInline", { bg = p.bg_red })

  -- neogit
  hi("NeogitBranch", { fg = p.purple, bold = true })
  hi("NeogitRemote", { fg = p.green, bold = true })
  hi("NeogitHunkHeader", { fg = p.fg, bg = p.bg3 })
  hi("NeogitHunkHeaderHighlight", { fg = p.fg, bg = p.bg3, bold = true })
  hi("NeogitDiffContext", { bg = p.bg1 })
  hi("NeogitDiffContextHighlight", { bg = p.bg2 })
  hi("NeogitDiffAdd", { fg = p.green, bg = p.bg_green })
  hi("NeogitDiffAddHighlight", { fg = p.green, bg = p.bg_green })
  hi("NeogitDiffDelete", { fg = p.red, bg = p.bg_red })
  hi("NeogitDiffDeleteHighlight", { fg = p.red, bg = p.bg_red })
  hi("NeogitStagedChanges", { fg = p.purple, bold = true })
  hi("NeogitUnstagedChanges", { fg = p.purple, bold = true })
  hi("NeogitUntrackedFiles", { fg = p.purple, bold = true })
  hi("NeogitRecentCommits", { fg = p.purple, bold = true })
  hi("NeogitCommitViewHeader", { fg = p.purple, bg = p.bg2, bold = true })
  hi("NeogitFilePath", { fg = p.blue, italic = true })
  hi("NeogitObjectId", { fg = p.purple })
  hi("NeogitGraphAuthor", { fg = p.orange })
  hi("NeogitGraphRed", { fg = p.red })
  hi("NeogitGraphGreen", { fg = p.green })
  hi("NeogitGraphYellow", { fg = p.yellow })
  hi("NeogitGraphBlue", { fg = p.blue })
  hi("NeogitGraphPurple", { fg = p.purple })
  hi("NeogitGraphOrange", { fg = p.orange })
  hi("NeogitGraphCyan", { fg = p.aqua })

  -- nvim-dap-ui
  hi("DapUIScope", { fg = p.aqua, bold = true })
  hi("DapUIType", { fg = p.yellow })
  hi("DapUIDecoration", { fg = p.aqua })
  hi("DapUIThread", { fg = p.green })
  hi("DapUIStoppedThread", { fg = p.aqua })
  hi("DapUISource", { fg = p.purple })
  hi("DapUILineNumber", { fg = p.aqua })
  hi("DapUIFloatBorder", { fg = p.aqua })
  hi("DapUIWatchesEmpty", { fg = p.red })
  hi("DapUIWatchesValue", { fg = p.green })
  hi("DapUIWatchesError", { fg = p.red })
  hi("DapUIBreakpointsPath", { fg = p.aqua })
  hi("DapUIBreakpointsInfo", { fg = p.green })
  hi("DapUIBreakpointsCurrentLine", { fg = p.green, bold = true })
  hi("DapUIBreakpointsLine", { fg = p.aqua })
  hi("DapUIBreakpointsDisabledLine", { fg = p.grey0 })
  hi("DapUICurrentFrameName", { fg = p.green, bold = true })
  hi("DapUIStepOver", { fg = p.aqua })
  hi("DapUIStepInto", { fg = p.aqua })
  hi("DapUIStepBack", { fg = p.aqua })
  hi("DapUIStepOut", { fg = p.aqua })
  hi("DapUIStop", { fg = p.red })
  hi("DapUIPlayPause", { fg = p.green })
  hi("DapUIRestart", { fg = p.green })
  hi("DapUIUnavailable", { fg = p.grey0 })
  hi("DapUIModifiedValue", { fg = p.aqua, bold = true })

  -- neotest
  hi("NeotestPassed", { fg = p.green })
  hi("NeotestFailed", { fg = p.red })
  hi("NeotestRunning", { fg = p.yellow })
  hi("NeotestSkipped", { fg = p.grey1 })
  hi("NeotestUnknown", { fg = p.grey1 })
  hi("NeotestNamespace", { fg = p.purple })
  hi("NeotestFile", { fg = p.aqua })
  hi("NeotestDir", { fg = p.aqua })
  hi("NeotestIndent", { fg = p.grey0 })
  hi("NeotestExpandMarker", { fg = p.grey0 })
  hi("NeotestAdapterName", { fg = p.purple, bold = true })
  hi("NeotestWinSelect", { fg = p.aqua, bold = true })
  hi("NeotestMarked", { fg = p.orange, bold = true })
  hi("NeotestTarget", { fg = p.red })
  hi("NeotestFocused", { bold = true })
  hi("NeotestWatching", { fg = p.yellow })

  -- snacks.nvim
  hi("SnacksPickerMatch", { fg = p.green, bold = true })
  hi("SnacksPickerDir", { fg = p.grey1 })
  hi("SnacksPickerFile", { fg = p.fg })
  hi("SnacksPickerTitle", { fg = p.orange, bold = true })
  hi("SnacksPickerBorder", { fg = p.grey1 })
  hi("SnacksPickerPrompt", { fg = p.green })
  hi("SnacksPickerCol", { fg = p.grey0 })
  hi("SnacksPickerRow", { fg = p.grey0 })
  hi("SnacksPickerComment", { fg = p.grey1 })
  hi("SnacksPickerSpecial", { fg = p.purple })
  hi("SnacksPickerTotals", { fg = p.grey1 })
  hi("SnacksPickerSelected", { fg = p.green, bold = true })
  hi("SnacksPickerIdx", { fg = p.orange })
  hi("SnacksPickerTree", { fg = p.grey0 })
  hi("SnacksNotifierInfo", { fg = p.blue })
  hi("SnacksNotifierWarn", { fg = p.yellow })
  hi("SnacksNotifierError", { fg = p.red })
  hi("SnacksNotifierDebug", { fg = p.grey1 })
  hi("SnacksNotifierTrace", { fg = p.purple })
  hi("SnacksNotifierIconInfo", { fg = p.blue })
  hi("SnacksNotifierIconWarn", { fg = p.yellow })
  hi("SnacksNotifierIconError", { fg = p.red })
  hi("SnacksNotifierIconDebug", { fg = p.grey1 })
  hi("SnacksNotifierIconTrace", { fg = p.purple })
  hi("SnacksNotifierTitleInfo", { fg = p.blue, bold = true })
  hi("SnacksNotifierTitleWarn", { fg = p.yellow, bold = true })
  hi("SnacksNotifierTitleError", { fg = p.red, bold = true })
  hi("SnacksNotifierTitleDebug", { fg = p.grey1, bold = true })
  hi("SnacksNotifierTitleTrace", { fg = p.purple, bold = true })
  hi("SnacksNotifierBorderInfo", { fg = p.blue })
  hi("SnacksNotifierBorderWarn", { fg = p.yellow })
  hi("SnacksNotifierBorderError", { fg = p.red })
  hi("SnacksNotifierBorderDebug", { fg = p.grey1 })
  hi("SnacksNotifierBorderTrace", { fg = p.purple })
  hi("SnacksDashboardHeader", { fg = p.green })
  hi("SnacksDashboardFooter", { fg = p.grey1 })
  hi("SnacksDashboardIcon", { fg = p.orange })
  hi("SnacksDashboardKey", { fg = p.aqua })
  hi("SnacksDashboardDesc", { fg = p.fg })
  hi("SnacksDashboardTitle", { fg = p.orange, bold = true })
  hi("SnacksDashboardSpecial", { fg = p.purple })
  hi("SnacksIndent", { fg = p.bg4 })
  hi("SnacksIndentScope", { fg = p.grey0 })

  -- trouble.nvim
  hi("TroubleText", { fg = p.fg })
  hi("TroubleSource", { fg = p.grey1 })
  hi("TroubleCode", { fg = p.grey1 })
  hi("TroubleCount", { fg = p.purple, bold = true })
  hi("TroubleError", { fg = p.red })
  hi("TroubleWarning", { fg = p.yellow })
  hi("TroubleInformation", { fg = p.blue })
  hi("TroubleHint", { fg = p.green })
  hi("TroubleFile", { fg = p.aqua })
  hi("TroubleLocation", { fg = p.grey1 })
  hi("TroubleFoldIcon", { fg = p.grey1 })
  hi("TroubleIndent", { fg = p.grey0 })
  hi("TroubleSignError", { fg = p.red })
  hi("TroubleSignWarning", { fg = p.yellow })
  hi("TroubleSignInformation", { fg = p.blue })
  hi("TroubleSignHint", { fg = p.green })

  -- which-key.nvim
  hi("WhichKey", { fg = p.red })
  hi("WhichKeyGroup", { fg = p.orange })
  hi("WhichKeySeparator", { fg = p.grey0 })
  hi("WhichKeyDesc", { fg = p.fg })
  hi("WhichKeyValue", { fg = p.grey1 })
  hi("WhichKeyFloat", { bg = p.bg2 })
  hi("WhichKeyBorder", { fg = p.grey1, bg = p.bg2 })

  -- noice.nvim
  hi("NoiceCmdline", { fg = p.fg })
  hi("NoiceCmdlineIcon", { fg = p.green })
  hi("NoiceCmdlineIconSearch", { fg = p.yellow })
  hi("NoiceCmdlinePopup", { fg = p.fg, bg = p.bg2 })
  hi("NoiceCmdlinePopupBorder", { fg = p.grey1, bg = p.bg2 })
  hi("NoiceCmdlinePopupBorderSearch", { fg = p.yellow, bg = p.bg2 })
  hi("NoiceConfirm", { fg = p.fg, bg = p.bg2 })
  hi("NoiceConfirmBorder", { fg = p.grey1, bg = p.bg2 })
  hi("NoiceMini", { fg = p.fg, bg = p.bg3 })
  hi("NoicePopup", { fg = p.fg, bg = p.bg2 })
  hi("NoicePopupBorder", { fg = p.grey1, bg = p.bg2 })
  hi("NoicePopupmenu", { fg = p.fg, bg = p.bg3 })
  hi("NoicePopupmenuBorder", { fg = p.grey1, bg = p.bg3 })
  hi("NoicePopupmenuMatch", { fg = p.green, bold = true })
  hi("NoicePopupmenuSelected", { fg = p.bg0, bg = p.green })
  hi("NoiceScrollbar", { bg = p.bg3 })
  hi("NoiceScrollbarThumb", { bg = p.grey0 })
  hi("NoiceSplit", { fg = p.fg, bg = p.bg0 })
  hi("NoiceSplitBorder", { fg = p.grey1 })
  hi("NoiceVirtualText", { fg = p.grey1 })
  hi("NoiceFormatProgressDone", { fg = p.bg0, bg = p.green })
  hi("NoiceFormatProgressTodo", { fg = p.fg, bg = p.bg3 })
  hi("NoiceLspProgressClient", { fg = p.green, bold = true })
  hi("NoiceLspProgressSpinner", { fg = p.purple })
  hi("NoiceLspProgressTitle", { fg = p.fg })
  hi("NoiceCompletionItemKindDefault", { fg = p.fg })
  hi("NoiceCompletionItemKindKeyword", { fg = p.red })
  hi("NoiceCompletionItemKindVariable", { fg = p.fg })
  hi("NoiceCompletionItemKindConstant", { fg = p.purple })
  hi("NoiceCompletionItemKindReference", { fg = p.fg })
  hi("NoiceCompletionItemKindValue", { fg = p.purple })
  hi("NoiceCompletionItemKindFunction", { fg = p.green })
  hi("NoiceCompletionItemKindMethod", { fg = p.green })
  hi("NoiceCompletionItemKindConstructor", { fg = p.green })
  hi("NoiceCompletionItemKindClass", { fg = p.yellow })
  hi("NoiceCompletionItemKindInterface", { fg = p.yellow })
  hi("NoiceCompletionItemKindStruct", { fg = p.yellow })
  hi("NoiceCompletionItemKindEvent", { fg = p.orange })
  hi("NoiceCompletionItemKindEnum", { fg = p.yellow })
  hi("NoiceCompletionItemKindUnit", { fg = p.purple })
  hi("NoiceCompletionItemKindModule", { fg = p.yellow })
  hi("NoiceCompletionItemKindProperty", { fg = p.blue })
  hi("NoiceCompletionItemKindField", { fg = p.blue })
  hi("NoiceCompletionItemKindTypeParameter", { fg = p.yellow })
  hi("NoiceCompletionItemKindEnumMember", { fg = p.purple })
  hi("NoiceCompletionItemKindOperator", { fg = p.orange })
  hi("NoiceCompletionItemKindSnippet", { fg = p.aqua })
  hi("NoiceCompletionItemKindText", { fg = p.fg })
  hi("NoiceCompletionItemKindFile", { fg = p.aqua })
  hi("NoiceCompletionItemKindFolder", { fg = p.green })
  hi("NoiceCompletionItemKindColor", { fg = p.orange })

  -- blink.cmp
  hi("BlinkCmpLabel", { fg = p.fg })
  hi("BlinkCmpLabelDeprecated", { fg = p.grey0, strikethrough = true })
  hi("BlinkCmpLabelMatch", { fg = p.green, bold = true })
  hi("BlinkCmpLabelDetail", { fg = p.grey1 })
  hi("BlinkCmpLabelDescription", { fg = p.grey1 })
  hi("BlinkCmpKind", { fg = p.purple })
  hi("BlinkCmpKindText", { fg = p.fg })
  hi("BlinkCmpKindMethod", { fg = p.green })
  hi("BlinkCmpKindFunction", { fg = p.green })
  hi("BlinkCmpKindConstructor", { fg = p.green })
  hi("BlinkCmpKindField", { fg = p.blue })
  hi("BlinkCmpKindVariable", { fg = p.fg })
  hi("BlinkCmpKindClass", { fg = p.yellow })
  hi("BlinkCmpKindInterface", { fg = p.yellow })
  hi("BlinkCmpKindModule", { fg = p.yellow })
  hi("BlinkCmpKindProperty", { fg = p.blue })
  hi("BlinkCmpKindUnit", { fg = p.purple })
  hi("BlinkCmpKindValue", { fg = p.purple })
  hi("BlinkCmpKindEnum", { fg = p.yellow })
  hi("BlinkCmpKindKeyword", { fg = p.red })
  hi("BlinkCmpKindSnippet", { fg = p.aqua })
  hi("BlinkCmpKindColor", { fg = p.orange })
  hi("BlinkCmpKindFile", { fg = p.aqua })
  hi("BlinkCmpKindReference", { fg = p.fg })
  hi("BlinkCmpKindFolder", { fg = p.green })
  hi("BlinkCmpKindEnumMember", { fg = p.purple })
  hi("BlinkCmpKindConstant", { fg = p.purple })
  hi("BlinkCmpKindStruct", { fg = p.yellow })
  hi("BlinkCmpKindEvent", { fg = p.orange })
  hi("BlinkCmpKindOperator", { fg = p.orange })
  hi("BlinkCmpKindTypeParameter", { fg = p.yellow })
  hi("BlinkCmpMenu", { fg = p.fg, bg = p.bg3 })
  hi("BlinkCmpMenuBorder", { fg = p.grey1, bg = p.bg3 })
  hi("BlinkCmpMenuSelection", { fg = p.bg0, bg = p.green })
  hi("BlinkCmpDoc", { fg = p.fg, bg = p.bg2 })
  hi("BlinkCmpDocBorder", { fg = p.grey1, bg = p.bg2 })
  hi("BlinkCmpDocCursorLine", { bg = p.bg3 })
  hi("BlinkCmpSignatureHelp", { fg = p.fg, bg = p.bg2 })
  hi("BlinkCmpSignatureHelpBorder", { fg = p.grey1, bg = p.bg2 })
  hi("BlinkCmpSignatureHelpActiveParameter", { fg = p.orange, bold = true })

  -- flash.nvim
  hi("FlashBackdrop", { fg = p.grey0 })
  hi("FlashMatch", { fg = p.fg, bg = p.bg3 })
  hi("FlashCurrent", { fg = p.fg, bg = p.bg_yellow })
  hi("FlashLabel", { fg = "#00dfff", bold = true })

  -- mini.nvim
  hi("MiniIndentscopeSymbol", { fg = p.grey0 })
  hi("MiniIndentscopeSymbolOff", { fg = p.grey0 })

  -- nvim-cmp (fallback)
  hi("CmpItemAbbr", { fg = p.fg })
  hi("CmpItemAbbrDeprecated", { fg = p.grey0, strikethrough = true })
  hi("CmpItemAbbrMatch", { fg = p.green, bold = true })
  hi("CmpItemAbbrMatchFuzzy", { fg = p.green, bold = true })
  hi("CmpItemKind", { fg = p.purple })
  hi("CmpItemMenu", { fg = p.grey1 })
end

return M
